"""Initial migration.


Revision ID: 88be59ec3a3f
Revises:
Create Date: 2022-10-11 18:19:16.239295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88be59ec3a3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_types = op.create_table(
        'transaction_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.Text(), nullable=False),
        sa.Column('hash', sa.Text(), nullable=False),
        sa.Column('cash', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'transactions',
        sa.Column(
            'transaction_id',
            sa.Integer(),
            autoincrement=True,
            nullable=False
        ),
        sa.Column('symbol', sa.String(length=10), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('shares', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('transaction_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['transaction_type_id'],
            ['transaction_types.id'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f(
        'ix_transactions_timestamp'),
        'transactions',
        ['timestamp'],
        unique=False
    )
    op.bulk_insert(transaction_types, [
        {'type': 'PURCHASE'},
        {'type': 'SALE'},
    ])
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     'sqlite_sequence',
    #     sa.Column('name', sa.NullType(), nullable=True),
    #     sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('transaction_types')
    # ### end Alembic commands ###
